# Generated by Django 2.0.6 on 2018-08-04 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('type', models.CharField(max_length=255)),
                ('image_path', models.FilePathField()),
            ],
        ),
        migrations.CreateModel(
            name='Produce_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Farm')),
                ('produce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Produce')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='produce_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Produce'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
